/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/FWorker.glb -t -r public
*/

import * as THREE from "three";
import { FC, useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTFActions, GLTFResult } from "./@types/FWorker3DModelTypes";
import {
  Generic3DModelProps,
  NPCloopableAnimationClips,
} from "../AbstractPersonel/@types/Generic3DModelProps";
import NPCanimationsByMachineStateMap from "../AbstractPersonel/helper/NPCanimationsByMachineStateMap";
import getAnimationClipMilliseconds from "../../../lib/getAnimationClipDuration";

const FWorker3DModel: FC<Generic3DModelProps> = ({ state, ...props }) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/FWorker.glb"
  ) as GLTFResult;
  // @ts-ignore
  const { actions } = useAnimations<GLTFActions>(animations, group);

  useEffect(() => {
    // @ts-ignore
    const availableAnimations = NPCanimationsByMachineStateMap?.get(state);
    const currentAnimation = availableAnimations
      ? availableAnimations[
          Math.floor(Math.random() * availableAnimations.length)
        ]
      : undefined;

    if (NPCloopableAnimationClips.includes(currentAnimation as string)) {
      actions[currentAnimation]?.reset().fadeIn(0.2).play();

      return () => {
        actions[currentAnimation]?.fadeOut(0.2);
      };
    } else {
      const secondsOfDeathAnimation = getAnimationClipMilliseconds(
        actions,
        currentAnimation
      );
      actions[currentAnimation]?.getClip().duration;
      actions[currentAnimation]?.reset().play();

      setTimeout(() => {
        actions[currentAnimation]?.stop();
      }, secondsOfDeathAnimation);
    }

    return () => {
      actions[currentAnimation]?.fadeOut(0.2);
    };
  }, [state]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group name="Worker_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Worker_Body_1"
              geometry={nodes.Worker_Body_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Worker_Body_1.skeleton}
            />
            <skinnedMesh
              name="Worker_Body_2"
              geometry={nodes.Worker_Body_2.geometry}
              material={materials.Worker_Vest}
              skeleton={nodes.Worker_Body_2.skeleton}
            />
            <skinnedMesh
              name="Worker_Body_3"
              geometry={nodes.Worker_Body_3.geometry}
              material={materials.Worker_Yellow}
              skeleton={nodes.Worker_Body_3.skeleton}
            />
            <skinnedMesh
              name="Worker_Body_4"
              geometry={nodes.Worker_Body_4.geometry}
              material={materials.White}
              skeleton={nodes.Worker_Body_4.skeleton}
            />
          </group>
          <group name="Worker_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Worker_Feet_1"
              geometry={nodes.Worker_Feet_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Worker_Feet_1.skeleton}
            />
            <skinnedMesh
              name="Worker_Feet_2"
              geometry={nodes.Worker_Feet_2.geometry}
              material={materials.Black}
              skeleton={nodes.Worker_Feet_2.skeleton}
            />
          </group>
          <group name="Worker_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Worker_Head_1"
              geometry={nodes.Worker_Head_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Worker_Head_1.skeleton}
            />
            <skinnedMesh
              name="Worker_Head_2"
              geometry={nodes.Worker_Head_2.geometry}
              material={materials.Worker_Yellow}
              skeleton={nodes.Worker_Head_2.skeleton}
            />
            <skinnedMesh
              name="Worker_Head_3"
              geometry={nodes.Worker_Head_3.geometry}
              material={materials.DarkBrown}
              skeleton={nodes.Worker_Head_3.skeleton}
            />
            <skinnedMesh
              name="Worker_Head_4"
              geometry={nodes.Worker_Head_4.geometry}
              material={materials.Brown}
              skeleton={nodes.Worker_Head_4.skeleton}
            />
          </group>
          <group name="Worker_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Worker_Legs_1"
              geometry={nodes.Worker_Legs_1.geometry}
              material={materials.Brown_02}
              skeleton={nodes.Worker_Legs_1.skeleton}
            />
            <skinnedMesh
              name="Worker_Legs_2"
              geometry={nodes.Worker_Legs_2.geometry}
              material={materials.Brown2}
              skeleton={nodes.Worker_Legs_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/FWorker.glb");

export default FWorker3DModel;
