/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/Cowcell.gltf -t -r public
*/
import {
  CollisionEnterHandler,
  CuboidCollider,
  RigidBody,
} from "@react-three/rapier";

import { Hitboxes } from "../../../lib/object3DHelper";
import { PositionalAudio } from "@react-three/drei";
import { useControls } from "leva";
import { useState } from "react";

// type GLTFResult = GLTF & {
//   nodes: {
//     Cow_1: THREE.Mesh;
//     Cow_2: THREE.Mesh;
//     Cow_3: THREE.Mesh;
//     Cow_4: THREE.Mesh;
//     Cow_5: THREE.Mesh;
//     Cow_6: THREE.Mesh;
//     Cow_7: THREE.Mesh;
//     foodcontainer: THREE.Mesh;
//     Cylinder001: THREE.Mesh;
//     Cylinder002: THREE.Mesh;
//     Cube001: THREE.Mesh;
//     Cube002: THREE.Mesh;
//     Cube003: THREE.Mesh;
//     Cube004: THREE.Mesh;
//     Cylinder003: THREE.Mesh;
//     Cylinder004: THREE.Mesh;
//     Cylinder005: THREE.Mesh;
//     Cylinder006: THREE.Mesh;
//     Cylinder007: THREE.Mesh;
//     Cylinder008: THREE.Mesh;
//     Cylinder009: THREE.Mesh;
//     Cylinder010: THREE.Mesh;
//     Cylinder011: THREE.Mesh;
//     Cylinder012: THREE.Mesh;
//     Cylinder013: THREE.Mesh;
//     Cylinder014: THREE.Mesh;
//     Cube005: THREE.Mesh;
//     Cube006: THREE.Mesh;
//   };
//   materials: {
//     Main: THREE.MeshStandardMaterial;
//     Main_Light: THREE.MeshStandardMaterial;
//     Muzzle: THREE.MeshStandardMaterial;
//     Hooves: THREE.MeshStandardMaterial;
//     Eye_Black: THREE.MeshStandardMaterial;
//     Eye_White: THREE.MeshStandardMaterial;
//     Horns: THREE.MeshStandardMaterial;
//     Plastic: THREE.MeshStandardMaterial;
//     metal: THREE.MeshStandardMaterial;
//     Column: THREE.MeshStandardMaterial;
//   };
// };

export default function PhysicalCowCell() {
  const { px, pz, dx, dz } = useControls({
    px: { value: 5, max: 30, min: -30, step: 0.1 },
    pz: { value: -1, max: 30, min: -30, step: 0.1 },
    dx: { value: 2, max: 30, min: -30, step: 0.1 },
    dz: { value: 1.2, max: 30, min: -30, step: 0.1 },
  });
  const [soundUrl, setSoundUrl] = useState("");

  const collisionEnterHandler = (({ other: { rigidBodyObject } }) => {
    setSoundUrl(
      [Hitboxes.HORNS, Hitboxes.HOOSES].includes(String(rigidBodyObject?.name))
        ? "/sounds/CowPen/cow-hit-cell.mp3"
        : ""
    );
  }) as CollisionEnterHandler;

  return (
    <RigidBody
      type={"fixed"}
      colliders={false}
      restitution={0}
      friction={3}
      density={500}
    >
      <CuboidCollider
        onCollisionEnter={collisionEnterHandler}
        position={[0, 0.5, -2]}
        args={[2, 0.5, 0.05]}
      />

      <CuboidCollider
        onCollisionEnter={collisionEnterHandler}
        position={[0, 0.5, 0.5]}
        args={[2, 0.5, 0.05]}
      />

      <CuboidCollider
        onCollisionEnter={collisionEnterHandler}
        position={[-2, 0.5, -0.75]}
        rotation={[0, Math.PI, 0]}
        args={[0.05, 0.5, 1.2]}
      />

      <CuboidCollider
        onCollisionEnter={collisionEnterHandler}
        position={[2, 0.5, -0.75]}
        rotation={[0, Math.PI, 0]}
        args={[0.05, 0.5, 1.2]}
      />

      <CuboidCollider position={[5, 0.5, 3.5]} args={[2, 0.5, 1.5]} />
      <CuboidCollider position={[5, 0.5, -0.8]} args={[2, 0.5, 1.2]} />
      <CuboidCollider position={[5, 0.5, -4.5]} args={[2, 0.5, dz]} />

      <CuboidCollider position={[0, 0.5, -4.5]} args={[2, 0.5, dz]} />
      <CuboidCollider position={[0, 0.5, 3.5]} args={[2, 0.5, 1.5]} />

      <CuboidCollider position={[-5, 0.5, -4.5]} args={[2, 0.5, dz]} />
      <CuboidCollider position={[-5, 0.5, -0.8]} args={[2, 0.5, 1.2]} />

      <CuboidCollider position={[-5, 0.5, 3.5]} args={[2, 0.5, 1.5]} />
      {soundUrl && (
        <PositionalAudio
          autoplay
          loop={false}
          load
          url={soundUrl}
          distance={0.2}
        />
      )}
    </RigidBody>
  );
}
